### ISSUE TITLE
Portable extension should use produce instead of create

### ISSUE THREAD

**Issue by ehsavoie** [smallrye/smallrye-llm#20]
Using producer instead of create removes the need for a CDI.current() call

**Comment by TheEliteGentleman** [comment]
I used `BeanManager` in my codebase since it's injected on each lifecycle directly.

Maybe have this type of solution? https://github.com/sinditech/sindi-langchain4j/blob/main/sindi-langchain4j-jakartaee-portable-extension/src/main/java/za/co/sindi/langchain4j/spi/LangChainAiServiceExtension.java

**Comment by Emily-Jiang** [comment]
fixed
