### ISSUE TITLE
LLM APIs

### ISSUE THREAD

**Issue by Emily-Jiang** [smallrye/smallrye-llm#3]
Do we need to create APIs (minimum Java 11) or just wrap LangChain4J?

**Comment by yblazart** [comment]
Hello, tbo, I would say I'd prefer to have a sort of "facade" in API to not show directly langchain4j, have a sort of SPI that let us decide wether to use langchain4j or not in future. To start quickly, extensions will do the glue code to link to langchain, but why not thinking to do similar stuffes like spring ai in future ?

**Comment by Emily-Jiang** [comment]
We discussed at today's call. It was suggested to adopt LangChain4J and integrate with MicroProfile. @yblazart please use this issue to link to your PR. We are looking forward to reviewing your PR.

**Comment by yblazart** [comment]
Oo, normally Antoine should had sent a message asking to delay the meeting to next week as we were not available today to present the current work. Ok, I will link the PR to this issue, but I have some changes to push.
