### ISSUE TITLE
Create new module for testing another way from langchain4j

### ISSUE THREAD

**Issue by yblazart** [smallrye/smallrye-llm#30]
After lot of discussions with everybody, we decided to try to get inspiration from Srping AI and use a Rest client with Open AI rest api.

Then goal is to create a new module with submodule to start experimentation. We should use testcontainer to launch a light model for integration tests if possible.

We should keep the structure of a core module, on wich we add portable and BCE extension.

**Comment by Emily-Jiang** [comment]
We used the injection framework.
